---
Name: elemental-preview-all-elements
Except:
  environment: live
---
DNADesign\Elemental\Models\ElementalArea:
  extensions:
    - Sunnysideup\PreviewAllElements\ElementalAreaExtension

PageController:
  extensions:
    - Sunnysideup\PreviewAllElements\PageExtension
